### ISSUE TITLE
Missing Model file

### ISSUE THREAD

**Issue by mustansarfiaz** [xinliu20/GraphCSPN_ECCV2022#1]
Dear Liu,

I think you missed the model file to upload it. please cross-check it

**Comment by xinliu20** [comment]
Dear Fiaz,

Thank you for your interest in our work. The codebase will be complete very soon as we are currently refactoring the code. Please stay tuned.

Best,
Xin Liu

**Comment by alexDJ-arch** [comment]
@xinliu20 
Dear Liu,
I'm wondering if you could provide the model code recently, thank you very much!

**Comment by xinliu20** [comment]
@dongjinmingDJM 
Dear Dong,
Thank you for your interest in our work. We plan to update the codebase in this month (after the busy cvpr period).
